version: "3"

services:
  db:
    # image right from docker
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - MYSQL:/var/lib/mysql

  nextcloud:
    # image right from docker
    image: nextcloud:25
    restart: always
    ports:
      - "80:80"
    volumes:
      - NEXTCLOUD:/var/www/html
      - ./config:/var/www/html/config
    depends_on:
      - db

volumes:
  MYSQL:
  NEXTCLOUD:
